<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<UseWPF>true</UseWPF>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageIconUrl>https://raw.githubusercontent.com/ButchersBoy/Dragablz/master/Resources/D32.png</PackageIconUrl>
		<PackageLicenseExpression></PackageLicenseExpression>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageProjectUrl>http://dragablz.net</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ButchersBoy/Dragablz</RepositoryUrl>
		<PackageTags>WPF TabControl Tab Tearable</PackageTags>
		<PackageReleaseNotes>Support for .NET 10</PackageReleaseNotes>
		<RepositoryType>git</RepositoryType>		
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<OutputPath>..\bin\Debug</OutputPath>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<OutputPath>..\bin\Release</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>
